Add close-popup files
tinyfish-io/agentql pull request #76
Opened 2024-10-29 17:36 UTC by SuveenE-TF

Add close-popup example
Update README.md

2024-10-29 19:29 UTC, rachelnabors requested changes

2024-10-29 19:29 UTC, rachelnabors commented on javascript-sdk/examples/close-popup/README.md
> +- Save this javascript file locally as **close-popup.js**
```suggestion
- Save this JavaScript file locally as **close-popup.js**
```

2024-10-29 19:29 UTC, rachelnabors approved these changes

2024-10-29 23:35 UTC, frankfeng98 requested changes

2024-10-29 23:35 UTC, frankfeng98 commented on javascript-sdk/examples/close-popup/close-popup.js
> +  configure({ apiKey: process.env.AGENTQL_API_KEY });
We're planning to remove this line to configure API key from example files.

2024-10-29 23:35 UTC, frankfeng98 commented on javascript-sdk/examples/close-popup/close-popup.js
> +require('dotenv').config();
Let's remove this from examples.

2024-10-30 17:22 UTC, frankfeng98 approved these changes

2024-10-30 18:02 UTC, merged