Close cookie popup js sdk
tinyfish-io/agentql pull request #77
Opened 2024-10-29 17:41 UTC by aarontantf

2024-10-29 17:56 UTC, frankfeng98 commented on javascript-sdk/examples/close-cookie-dialog/close-cookie-dialog.js
> +  configure({ apiKey: 'YOUR_API_KEY' });
We decided taht we will read in from environment variable here

2024-10-29 19:30 UTC, rachelnabors approved these changes

2024-10-29 19:30 UTC, rachelnabors commented on javascript-sdk/examples/close-cookie-dialog/README.md
> +- Save this js file locally as **close-cookie-dialog.js**
```suggestion
- Save this JavaScript file locally as **close-cookie-dialog.js**
```

2024-10-29 19:34 UTC, rachelnabors requested changes

2024-10-29 19:34 UTC, rachelnabors commented on javascript-sdk/examples/close-cookie-dialog/close-cookie-dialog.js
> +  configure({ apiKey: process.env.AGENTQL_API_KEY });
Recommend removing this and covering the API key in the installation instructions

2024-10-30 02:18 UTC, rachelnabors approved these changes

2024-10-30 18:41 UTC, merged