Compare Product Prices Example
tinyfish-io/agentql pull request #78
Opened 2024-10-29 17:42 UTC by jinyangTF

as titled

2024-10-29 19:30 UTC, rachelnabors approved these changes

2024-10-29 19:30 UTC, rachelnabors commented on javascript-sdk/examples/compare-product-prices/README.md
> +- Save this javascript file locally as **compare-product-prices.js**
```suggestion
- Save this JavvaScript file locally as **compare-product-prices.js**
```

2024-10-29 19:31 UTC, rachelnabors approved these changes

2024-10-29 19:34 UTC, rachelnabors requested changes

2024-10-29 19:34 UTC, rachelnabors commented on javascript-sdk/examples/compare-product-prices/README.md
> +- [Install AgentQL SDK](https://agentql-docs-opvm8e9cd-tiny-fish.vercel.app/javascript-sdk/installation)
```suggestion
- [Install AgentQL SDK](https://docs.agentql.com/javascript-sdk/installation)
```

2024-10-29 23:37 UTC, frankfeng98 requested changes

2024-10-29 23:37 UTC, frankfeng98 commented on javascript-sdk/examples/compare-product-prices/compare-product-prices.js
> +configure({ apiKey: process.env.AGENTQL_API_KEY });
We're planning to remove setting API key from examples.

2024-10-30 22:47 UTC, frankfeng98 approved these changes

2024-10-31 12:51 UTC, rachelnabors approved these changes

2024-10-31 16:17 UTC, merged