Add log-into-sites examples
tinyfish-io/agentql pull request #79
Opened 2024-10-29 17:50 UTC by SuveenE-TF

Add exmaple
Update README.md

2024-10-29 19:31 UTC, rachelnabors commented on javascript-sdk/examples/log-into-sites/README.md
> +- Save this javascript file locally as **log-into-sites.js**
```suggestion
- Save this JavaScript file locally as **log-into-sites.js**
```

2024-10-29 19:31 UTC, rachelnabors approved these changes

2024-10-29 19:33 UTC, rachelnabors requested changes

2024-10-29 19:33 UTC, rachelnabors commented on javascript-sdk/examples/log-into-sites/log-into-sites.js
> +  configure({ apiKey: process.env.AGENTQL_API_KEY });
I recommend removing this part and covering keys in the installation docs, not the sample apps

2024-10-30 22:49 UTC, frankfeng98 approved these changes

2024-10-30 23:12 UTC, merged