Tf 3906
tinyfish-io/agentql pull request #82
Opened 2024-10-29 18:10 UTC by wjwjtf

2024-10-31 16:09 UTC, colriot requested changes

2024-10-31 16:09 UTC, colriot commented on .stylelintrc.js
> -  extends: 'stylelint-config-ship-shape',
It seems to me that you IDE setup has inconsistent linting/formatting setup — can you please rollback all the changes to the files that are unrelated to your PR.

In general it's a good practice to look at the diff or your changes before committing and pushing them to make sure only intended changes will end up in this PR

2024-10-31 16:09 UTC, colriot commented on javascript-sdk/examples/interact-with-external-or-existing-browser/README.md
> +- Save this javascript file locally as **log-into-sites.js**
```suggestion
- Save this JavaScript file locally as **log-into-sites.js**
```

2024-10-31 16:09 UTC, colriot commented on javascript-sdk/examples/interact-with-external-or-existing-browser/README.md
> +# Example script: interact with external or existing browser
You have 2 blocks with 2 different scripts described. Pls, fix it.

The second bock has no links in markdown, seems like you copied plain text only

2024-10-31 16:09 UTC, colriot commented on javascript-sdk/examples/interact-with-external-or-existing-browser/interact-with-external-or-existing-browser.js
> +  const page = wrap(await browser.contexts()[0].newPage());
```suggestion
  const page = wrap(await browser.newPage());
```

2024-10-31 16:09 UTC, colriot commented
Can you update the name of the PR to have a valid messaging

2024-11-01 11:56 UTC, colriot requested changes
Some more things to fix

2024-11-01 11:56 UTC, colriot commented on javascript-sdk/examples/interact-with-external-or-existing-browser/README.md
> +- Save this JS file locally as interact-with-external-or-existing-browser.js
Pls, check out the formatting of the original README in Python folder and make sure it is similar. You lost formatting and links
```suggestion
- Save this JS file locally as **interact-with-external-or-existing-browser.js**
```

2024-11-01 11:56 UTC, colriot commented on javascript-sdk/examples/interact-with-external-or-existing-browser/interact-with-external-or-existing-browser.js
> +  //"""This function demonstrates how to open and interact with a new page your local browser."""
Triple quotes — Python style comments, JS uses it's own style. Also. make sure you preserve comments from original python file along the code itself

```suggestion
// This function demonstrates how to open and interact with a new page your local browser.
async function interactWithNewPageInLocalBrowser() {
```

2024-11-05 18:37 UTC, frankfeng98 commented
@wjwjtf Hi Wenjie! Let me know if u need help with this :)

2024-11-05 23:56 UTC, frankfeng98 commented
Closing this PR as it contains unrelated file changes. I will update the example

2024-11-05 23:56 UTC, closed without merging