add save / load authenticated session js sdk example.
tinyfish-io/agentql pull request #84
Opened 2024-10-29 18:58 UTC by lozzle

ran script and saw successful reload.

i think there's some js-ism way to open and close the browser session but i'm not totally sure.  please educate me if there's a better way to do this!

2024-10-29 23:18 UTC, frankfeng98 requested changes
The format issue could be resolved by CD into `javascript-sdk` folder, run `npm install` and then `npm run format`

2024-10-29 23:18 UTC, frankfeng98 commented on javascript-sdk/examples/save-and-load-authenticated-session/save-and-load-authenticated-session.js
> +  configure({ apiKey: process.env.API_KEY });
@rachelnabors and I are thinking about removing `configure` line and using `dotenv` line from examples. JS SDK currently supports directly read in AGENTQL_API_KEY as a backup option when retrieving API key. We will ask users to set API key as an environment variable in installation guide.

2024-10-29 23:18 UTC, frankfeng98 commented on javascript-sdk/examples/save-and-load-authenticated-session/README.md
> +- Save this python file locally as **save-and-load-authenticated-state.js**
Javascript file

2024-10-29 23:18 UTC, frankfeng98 commented on javascript-sdk/examples/save-and-load-authenticated-session/README.md
> +node save_and_load_authenticated_state.py
save-and-load-authenticated-state.js

2024-10-30 00:33 UTC, lozzle commented
sorry sorry, swapping between sapling and git confused me.  i think it's a bit better this time

2024-10-30 16:50 UTC, frankfeng98 approved these changes

2024-10-30 17:47 UTC, lozzle commented
sorry, also lost the changes where i ported in comments from the python version of this.  re-added that!

2024-10-30 17:49 UTC, merged